// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCcgnl5m9UKku6_XKbG_7PdLAqxKGKHvDk',
    appId: '1:607041989085:web:14cdebdf5e6bdb35776e34',
    messagingSenderId: '607041989085',
    projectId: 'fixitup-c9036',
    authDomain: 'fixitup-c9036.firebaseapp.com',
    storageBucket: 'fixitup-c9036.firebasestorage.app',
    measurementId: 'G-0WP1WE7VW2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDOKaLjx0AamkNmGHg3FN_dZ_h4dT6pDXQ',
    appId: '1:607041989085:android:1f876512f2259420776e34',
    messagingSenderId: '607041989085',
    projectId: 'fixitup-c9036',
    storageBucket: 'fixitup-c9036.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBj_Rw9LyeIwYUDgIqa2isYxu19AN2tHfA',
    appId: '1:607041989085:ios:1daa88c8a3f9319b776e34',
    messagingSenderId: '607041989085',
    projectId: 'fixitup-c9036',
    storageBucket: 'fixitup-c9036.firebasestorage.app',
    iosBundleId: 'com.payflow.payflow',
  );
}
